#include "gnuplot_output.h"
#include <fstream>
#include <iomanip>
#include <iostream>
#include <cstdlib>
#include <sstream>
#include <cmath>

// ============================================================
// 写入单步 .dat 文件
// ============================================================

void write_timestep_dat(const std::string& filename,
                        const WaveletFEMSolver& solver,
                        const MatrixXd& U,
                        double t,
                        int nx, int ny) {
    (void)t; // 时间戳未写入 .dat 文件本身（在 GIF 标题中显示）
    (void)U; // U 矩阵在此函数中不使用，reconstruct 使用 solver 内部历史

    std::ofstream out(filename);
    if (!out.is_open()) {
        throw std::runtime_error("Cannot open file: " + filename);
    }

    out << std::scientific << std::setprecision(8);

    double ax = solver.ax(), bx = solver.bx();
    double ay = solver.ay(), by = solver.by();
    double hx = (bx - ax) / (nx - 1);
    double hy = (by - ay) / (ny - 1);

    // 临时设置：该函数需要 solver.reconstruct(x, y, step) 接口
    // 这里使用 solver 的公开接口获取参数
    int n_basis = solver.num_basis();
    int k_min_val = solver.k_min();
    int res_j = solver.resolution_j();
    double pow2_j = 1 << res_j;
    double sqrt_pow2_j = std::sqrt(pow2_j);

    // 使用 U 矩阵直接做级数展开重构
    for (int i = 0; i < nx; ++i) {
        double x = ax + i * hx;
        for (int j = 0; j < ny; ++j) {
            double y = ay + j * hy;

            double sum = 0.0;
            for (int l = 0; l < n_basis; ++l) {
                int k_l = k_min_val + l;
                double arg_x = pow2_j * x - k_l;
                double phi_x = sqrt_pow2_j * solver.conn_table().eval_phi(arg_x);

                for (int m = 0; m < n_basis; ++m) {
                    int k_m = k_min_val + m;
                    double arg_y = pow2_j * y - k_m;
                    double phi_y = sqrt_pow2_j * solver.conn_table().eval_phi(arg_y);
                    sum += U(l, m) * phi_x * phi_y;
                }
            }

            out << sum;
            if (j < ny - 1) out << " ";
        }
        out << "\n";
    }

    out.close();
}

// ============================================================
// 写入 .dat（重载：接受 solver 的历史记录）
// ============================================================

static void write_timestep_dat(const std::string& filename,
                               const WaveletFEMSolver& solver,
                               int step) {
    double ax = solver.ax(), bx = solver.bx();
    double ay = solver.ay(), by = solver.by();
    int nv = solver.nviz();
    double hx = (bx - ax) / (nv - 1);
    double hy = (by - ay) / (nv - 1);

    std::ofstream out(filename);
    if (!out.is_open()) {
        throw std::runtime_error("Cannot open file: " + filename);
    }

    out << std::scientific << std::setprecision(8);

    for (int i = 0; i < nv; ++i) {
        double x = ax + i * hx;
        for (int j = 0; j < nv; ++j) {
            double y = ay + j * hy;
            double val = solver.reconstruct(x, y, step);
            out << val;
            if (j < nv - 1) out << " ";
        }
        out << "\n";
    }

    out.close();
}

// ============================================================
// 生成 GNUPlot 脚本并调用
// ============================================================

void generate_gif(const std::string& output_gif,
                  const std::vector<std::string>& dat_files,
                  const std::vector<double>& timestamps,
                  const std::string& title,
                  const ProblemConfig& config,
                  int delay_ms) {

    // 生成 GNUPlot 脚本
    std::string script_path = output_gif;
    size_t ext_pos = script_path.rfind(".gif");
    if (ext_pos != std::string::npos) {
        script_path.replace(ext_pos, 4, ".gp");
    } else {
        script_path += ".gp";
    }

    std::ofstream gp(script_path);
    if (!gp.is_open()) {
        throw std::runtime_error("Cannot create GNUPlot script: " + script_path);
    }

    int N = (int)dat_files.size();

    gp << "# GNUPlot script generated by WaveletFEM\n";
    gp << "set terminal gif animate delay " << delay_ms
       << " size 800,600 enhanced\n";
    gp << "set output '" << output_gif << "'\n\n";

    gp << "set xlabel 'x'\n";
    gp << "set ylabel 'y'\n";
    gp << "set xrange [" << config.ax << ":" << config.bx << "]\n";
    gp << "set yrange [" << config.ay << ":" << config.by << "]\n";
    gp << "set view map\n";
    gp << "set pm3d map interpolate 0,0\n";
    gp << "set palette defined ("
       << "0 'blue', 1 'cyan', 2 'yellow', 3 'red'"
       << ")\n";
    gp << "set cblabel 'u(x,y,t)'\n";
    gp << "set size square\n\n";

    gp << "# Helper: get timestamp index from file index\n";
    gp << "array T[" << N << "]\n";
    for (int i = 0; i < N; ++i) {
        gp << "T[" << (i + 1) << "] = " << timestamps[i] << "\n";
    }
    gp << "\n";

    gp << "do for [i=1:" << N << "] {\n";
    gp << "    filename = '" << dat_files[0] << "'\n";
    gp << "    if (i > 1) {\n";
    gp << "        filename = sprintf('";
    // 从第一个文件名提取模式
    std::string pattern = dat_files[0];
    // 假设文件名类似 step_XXXX.dat
    gp << pattern << "');\n";
    // 使用更简单的方式
    gp << "    }\n";
    gp << "    set title sprintf('" << title << "\\\\nt = %.4f', T[i])\n";
    gp << "    if (strstrt(filename, '.dat') || strstrt(filename, '.txt')) {\n";
    gp << "        splot filename matrix with image notitle\n";
    gp << "    }\n";
    gp << "}\n";

    // 简化版本：使用固定的文件名模式
    // 实际上，GNUPlot 的 do for 循环中使用 sprintf
    // 更可靠的写法：

    // 重写脚本为更简洁的版本
    gp.close();

    // 重写——使用更简洁且工作良好的脚本
    std::ofstream gp2(script_path);
    gp2 << "# GNUPlot script generated by WaveletFEM\n";
    gp2 << "set terminal gif animate delay " << delay_ms
        << " size 800,600 enhanced\n";
    gp2 << "set output '" << output_gif << "'\n\n";

    gp2 << "set xlabel 'x'\n";
    gp2 << "set ylabel 'y'\n";
    gp2 << "set xrange [" << config.ax << ":" << config.bx << "]\n";
    gp2 << "set yrange [" << config.ay << ":" << config.by << "]\n";
    gp2 << "set view map\n";
    gp2 << "set pm3d map interpolate 0,0\n";
    gp2 << "set palette defined ("
        << "0 'blue', 1 'cyan', 2 'yellow', 3 'red'"
        << ")\n";
    gp2 << "set cblabel 'u(x,y,t)'\n";
    gp2 << "set size square\n\n";

    // 逐帧输出
    gp2 << "array Timestamps[" << N << "]\n";
    for (int i = 0; i < N; ++i) {
        gp2 << "Timestamps[" << (i + 1) << "] = "
            << std::fixed << std::setprecision(6) << timestamps[i] << "\n";
    }

    for (int i = 0; i < N; ++i) {
        gp2 << "\nset title sprintf('" << title << "\\\\nt = %.4f', Timestamps["
            << (i + 1) << "])\n";
        gp2 << "splot '" << dat_files[i] << "' matrix with image notitle\n";
    }

    gp2.close();

    std::cout << "Generated GNUPlot script: " << script_path << std::endl;
    std::cout << "Output GIF: " << output_gif << std::endl;

    // 调用 gnuplot
    std::string cmd = "gnuplot \"" + script_path + "\"";
    std::cout << "Running: " << cmd << std::endl;

    int ret = std::system(cmd.c_str());
    if (ret != 0) {
        std::cerr << "Warning: gnuplot returned exit code " << ret << std::endl;
    } else {
        std::cout << "GIF generated successfully: " << output_gif << std::endl;
    }
}

// ============================================================
// 批量导出所有时间步
// ============================================================

void export_all_steps(const std::string& output_dir,
                      const WaveletFEMSolver& solver,
                      const std::vector<TimeStepRecord>& history,
                      const ProblemConfig& config) {

    std::vector<std::string> dat_files;
    std::vector<double> timestamps;

    int n_steps = (int)history.size();

    std::cout << "\n=== Exporting " << n_steps << " time steps ===\n";

    for (int step = 0; step < n_steps; ++step) {
        // 生成文件名
        std::ostringstream oss;
        oss << output_dir << "/step_" << std::setw(4) << std::setfill('0')
            << step << ".dat";
        std::string fname = oss.str();

        // 写入数据
        write_timestep_dat(fname, solver, step);

        dat_files.push_back(fname);
        timestamps.push_back(history[step].t);

        if ((step + 1) % 10 == 0 || step == n_steps - 1) {
            std::cout << "  Exported step " << (step + 1) << "/"
                      << n_steps << " (t = " << history[step].t << ")\r";
            std::cout.flush();
        }
    }
    std::cout << std::endl;

    // 生成 GIF
    std::string gif_path = output_dir + "/heat_evolution.gif";
    generate_gif(gif_path, dat_files, timestamps,
                 "2D Heat Equation - Wavelet Galerkin FEM",
                 config, 10);
}
